version: "3"

tasks:
  default:
    deps:
      - run

  run:
    cmds:
      - python -m helix.main

  test:
    cmds:
      - python -m pytest

  install:
    cmds:
      - python -m pip install -U pip
      - python -m pip install -r requirements.txt
