from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class WelcomeScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(600, 400))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet(u"background-color: #CADBDD")
        self.header = QLabel(self.centralwidget)
        self.header.setObjectName(u"header")
        self.header.setGeometry(QRect(0, 0, 811, 331))
        self.header.setPixmap(QPixmap(u"./assets/header.png"))
        self.logo = QLabel(self.centralwidget)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(30, 30, 241, 241))
        self.logo.setStyleSheet(u"background-color: transparent")
        self.logo.setPixmap(QPixmap(u"./assets/helix-logo.png"))
        self.logo.setScaledContents(False)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 360, 391, 61))
        font = QFont()
        font.setFamily(u"Helvetica")
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"background-color: transparent; color: #666666; font-size: 40px;")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(75, 450, 196, 61))
        font1 = QFont()
        font1.setPointSize(25)
        self.pushButton.setFont(font1)
        self.pushButton.setStyleSheet(u"color: #cadbdd; background-color: #666666; border-radius: 5px")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(570, 450, 196, 61))
        self.pushButton_2.setFont(font1)
        self.pushButton_2.setStyleSheet(u"color: #666666; border-radius: 5px")
        # MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QMenuBar(MainWindow)
        # self.menubar.setObjectName(u"menubar")
        # self.menubar.setGeometry(QRect(0, 0, 800, 24))
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QStatusBar(MainWindow)
        # self.statusbar.setObjectName(u"statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.header.setText("")
        self.logo.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Welcome, user!", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Dictionary", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"log out", None))
        self.pushButton.show()
        self.header.show()


